### ISSUE TITLE
grpc support in the future?

### ISSUE THREAD

**Issue by grapemix** [indradb/indradb#15]
Hi,

I am really glad there has an open source graph DB written in Rust. Thanks for the contribution to the community. Grpc based on protobuf can provide a pretty fast way to communicate across different lang and system. And setting up grpc is pretty easy too. Would you mind to consider adding grpc support in the future too(No hurry)? Thanks.

BTW, it may be a good idea to add indradb to those db comparison website to get some expose(or just to show off ;-) )

**Comment by ysimonson** [comment]
Thanks!

Have you tried grpc on rust? If so, how is it? Grpc is a fairly large/complex dependency, and I wouldn't want to pull it in unless there were a solid rust integration and there were some substantial gains by using it (either by easing interoperability, or by better performance, or preferably both.)

**Comment by ysimonson** [comment]
I've been digging into this lately. It would be a lot of work to create protobuf specifications out of the existing transaction trait and models. This is opposed to the current use of serde and a little bit of HTTP glue, which, because of serde's automatic (de-)serialization, requires _very_ little gymnastics.

I'm wondering if there's a way to get the best of both worlds (grpc-esque ease of language interoperability + serde-esque ease of development) but don't have an answer for that yet.

**Comment by ysimonson** [comment]
I'm going to close this out; see the comments in the gRPC PR for details
