### ISSUE TITLE
Q: in-mem + persistence?

### ISSUE THREAD

**Issue by martingronlund** [indradb/indradb#164]
Is in-mem faster than using a datastore? I would imagine so, but how much? If one desires operational throughput, in-mem would be the way, right?

A state can be described by either a seed and a simulation, a seed and a set of patches, or a dump of the whole state. Serializing a simulation of queries is likely hard, haha, but what about the other two?

How would one persist the state when using in-mem? It'd be great to be able to save both full state and queries over time, because this would enable both replays and restores.

I'm curious to hear what you think!

**Comment by martingronlund** [comment]
Oh and a question I also wanted to ask is:

How about a thread writing the state or the queries to disk reactively over time, while using in-mem?

**Comment by ysimonson** [comment]
Here's what the synthetic benchmarks give back:

```
test memory::bench_bulk_insert                        ... bench:  10,154,879 ns/iter (+/- 1,689,111)
test memory::bench_create_edge                        ... bench:         235 ns/iter (+/- 7)
test memory::bench_create_vertex                      ... bench:         309 ns/iter (+/- 18)
test memory::bench_get_edge_count                     ... bench:         100 ns/iter (+/- 1)
test memory::bench_get_edges                          ... bench:         164 ns/iter (+/- 9)
test memory::bench_get_vertices                       ... bench:         110 ns/iter (+/- 6)
test rdb::bench_bulk_insert                           ... bench:  77,581,017 ns/iter (+/- 15,529,549)
test rdb::bench_create_edge                           ... bench:       5,885 ns/iter (+/- 71)
test rdb::bench_create_vertex                         ... bench:       3,067 ns/iter (+/- 200)
test rdb::bench_get_edge_count                        ... bench:       1,530 ns/iter (+/- 14)
test rdb::bench_get_edges                             ... bench:         643 ns/iter (+/- 23)
test rdb::bench_get_vertices                          ... bench:         609 ns/iter (+/- 6)
```

Just spinning up a separate thread to dump state or a transaction log would be very slow. The work to make that sort of architecture fast would require a bunch of thought into fine-tuning data structures, caching, pointer swizzling, etc... at which point it'd just be re-inventing what rocksdb or sled already offers.

There is an alternative architecture for persisting in-memory results: forking. You'd fork the process, and dump a snapshot in one process while continuing to transact on the other. Copy-on-write semantics should ensure the overhead would be minimal. The downsides are that this wouldn't be portable beyond POSIX, and persisted results wouldn't be as reliable since they're intermittent snapshots. But it would be interesting to test.

**Comment by ysimonson** [comment]
(Experimental) effort in #170

**Comment by ysimonson** [comment]
OK, got it working. It doesn't use fork like I originally proposed, as it wasn't feasible to ensure that subsequent syscalls in the child were async-signal-safe. Instead, it's just a new function on the datastore (`sync`).

When called on the in-memory implementation, this will dump a bincode-serialized version to disk. A couple of caveats with this approach:

* It's slow, since it reserializes all of the data structures from scratch on every run.
* It requires a read lock, so updates to the datastore aren't possible while syncing is happening.

In the rocksdb datastore, I reused the same function to:

* Explicitly compact (as [used to happen after every bulk insert](https://github.com/indradb/indradb/pull/138), but was removed because it was too heavyweight.)
* Flush.

In sled it's a no-op.

**Comment by martingronlund** [comment]
Interesting!

The first idea that comes to mind is to optimize what we now have to incrementally serialize only changes (btw, do we have change streaming? Change streaming is really nice for reactive programming! I'm thinking of e.g. couchdb's change streams, but that whole db is eventually consistent - I wonder if it's an idea to loosen our consistency requirement in this area, like you alluded to with forking before)

**Comment by martingronlund** [comment]
Also inspired by Unity's ECS design, and there you would have read locks on a per-chunk basis, so writes could occur on the other chunks simultaneously. There however, everything is predictably happening in a loop. But the storage format and memory layout is great.

**Comment by ysimonson** [comment]
I think anything that needs better concurrency or non-explicit persistence can rely on the rocksdb or sled-based datastores, since they do the hard work of providing that while still offering reasonable query performance. It's not clear to me how it could be patched onto the in-memory datastore in a manner that doesn't have a performance penalty for non-contented queries.

Change streaming makes sense, though it's not supported at the moment. Feel free to open a separate ticket on that!
