### ISSUE TITLE
Docker images

### ISSUE THREAD

**Issue by ysimonson** [indradb/indradb#177]
For convenience, it’d be great to have docker images for running both the client and server CLIs.

**Comment by WatsonThink** [comment]
It's great.
Will a docker-compose consisting of a server image and a client image connected together satisfy your idea?
If so, can you assign this issue to me?

**Comment by ysimonson** [comment]
Hi @WatsonThink! Thanks for volunteering. Correct me of I'm wrong, but I think docker compose is generally used at the application level, to wire in/connect databases like IndraDB. Given that, I don't think docker compose is necessary. We'd just need to a couple of Dockerfiles/images for the client and server.

**Comment by WatsonThink** [comment]
Simpler answers are always good.
I thinks a only one docker file is required because the environment of the server and client is almost same.
A client container and server container from the same image are connecting each pother, is it okay?
If so, I will implement and write a document when using a docker.

**Comment by ysimonson** [comment]
Yup, that makes sense! Will give you the ticket.
