### ISSUE TITLE
Querying over hops between vertices 

### ISSUE THREAD

**Issue by CloseChoice** [indradb/indradb#180]
Would it be possible to query over multiple hops in terms of vertices or edges? So, e.g. introduce VertexDistanceQuery with a parameter (let's call it `dist`) that determine the distance which shall be taken into account. If `dist=2` and we query for a id `1`, then we'll get all vertices which are up to 2 edges away from `1`.

**Comment by bburdette** [comment]
You can chain PipeVertexQuery and PipeEdgeQuery to get something like that.  Though you might get some repeats - like a vertex could be 2 edges away from itself for instance.

**Comment by CloseChoice** [comment]
Thanks for the fast answer. Your answer led me to the `.inbound` and `.outbound` methods which are even simpler methods to get distant vertices or edges.

Would still like an out-of-the-box method for these queries, which I assume pretty standard in a graph-based db.

**Comment by ysimonson** [comment]
There's presently no way to do that in a single query, but it can be achieved with multiple queries as you've discovered and @bburdette suggested. `.inbound` and `.outbound` are simpler, but less performant since they'll restart the search at root for each value of `dist`, whereas piping will not.

The reason this isn't supported in a single query is that IndraDB generally follows the architecture outlined in TAO, which is purposefully simple in order to guarantee good query performance. I do think this use case is worth revisiting though, since this is part and parcel with what, e.g. GraphQL offers. Or alternatively, maybe it makes sense to provide a scripting/plugin layer where multiple queries can be executed more ergonomically, and without the back-and-forth between the client and server. That's something IndraDB offered before, but scrapped as the query interface got more sophisticated.
