### ISSUE TITLE
Why do we uses clone with queries?

### ISSUE THREAD

**Issue by sciencemanx** [indradb/indradb#66]
As in https://github.com/indradb/indradb/blob/master/lib/src/tests/properties.rs#L17. Why is it not sufficient to pass in the query object itself?

**Comment by ysimonson** [comment]
The various trait methods (like `get_vertex_properties`) take queries, rather than references to queries. This gives datastore implementations full ownership of the queries, and gives them flexibility to avoid cloning queries (or values in the queries) where applicable.

It does mean that queries have to be cloned when being passed in. In practice, the current approach should yield better performance, because when IndraDB is used through its capnp interface, the queries don't need to be cloned anyways. But it does add a little baggage when IndraDB is used via it's low-level rust interface (and in tests.)
