### ISSUE TITLE
Scalability for 500M vertices and 2Bn edges labelled by 1M indices.

### ISSUE THREAD

**Issue by panicfarm** [indradb/indradb#87]
We were thinking of using indraDb, but we could not find any metrics. The rest of our project is in Rust, so if we pick a Rust Graph DB, at least we can understand the code and possibly contribute.

Our data set has about 500M vertices and 2Bn directed edges. Each edge has an index from 0 to 1M (i.e. on average 2000 edges share the same index). We can have parallel edges with different indices. We need to be able to query for a desired index range. Also, each edge has another value attribute, and each vertex has one scalar attribute. We would have to add more vertices and edges as time goes on. We would like to host this on a single server with large memory. 

- Would indraDB scale for such a data set?
- How would you model such a data set in a graph DB (and in IndraDB specifically)? Should it be a one giant graph or maybe a series of 1M sub-graphs (e.g. one graph per each index value)?

**Comment by ysimonson** [comment]
The largest graph I've managed to index is the [english wikipedia dataset](https://github.com/indradb/wikipedia-example), 6m vertices, and I'd guesstimate 60m edges. Even for that dataset, indexing took several days. To be fair, a lot of that slowness is due to the python-based wikipedia indexer rather than IndraDB itself, so I can't give a fully confident answer to your question. But I'd guess that IndraDB cannot handle a dataset that large at this time.

As a test, indexing a 1M sub-graph in IndraDB makes a lot of sense. So long as there's a clean way to partition your graph, that should be fairly quick to test out on IndraDB. I'd love to know how that pans out if you do it. Every dataset is different, so it may turn up some interesting info on optimizations that could be made.

**Comment by ysimonson** [comment]
I take it back. I'm currently working on rewriting the wikipedia example to use rust in parts, and it runs way faster - like indexing in an hour rather than days. And that's including some fairly heavy client-side, non-IndraDB work going on (a great deal of disk I/O + hashing.)

Based off that, I think it's now safe to say that IndraDB can handle millions of vertices and tens to hundreds of millions of edges fine. I'm still not sure about the scale you're talking about, just because it hasn't been done yet to my knowledge, but it doesn't seem unlikely like it did before.

I'll close this out since I'm not sure there's anything actionable here, but please do post an update if you ever got around to trying this.
