### ISSUE TITLE
Any plan for query language support?

### ISSUE THREAD

**Issue by dgandhi17** [indradb/indradb#94]
Any plan to support query language like gremlin or cypher. Inshort what is the roadmap of features planed

**Comment by ysimonson** [comment]
IndraDB has its own query language, defined via capnp: https://github.com/indradb/indradb/blob/master/bin/indradb.capnp

This is better in that there's effectively no query parsing overhead, and it makes it easier to design fairly clean wrapper libraries, e.g. [python](https://github.com/indradb/python-client), which is employed in the [wikipedia example](https://github.com/indradb/wikipedia-example).

There's no plan to support other query languages, but I'd be happy to support anyone who did want to undertake that.

**Comment by dgandhi17** [comment]
Do you think the lib can adapt cypher language ? can you add little design details of the library so that it will help other to see how to fit something in the architecture

**Comment by ysimonson** [comment]
IndraDB isn't optimized for running comparison checks on properties, and the query language is purposefully designed to not expose functionality that it can't execute efficiently. If comparisons on properties are necessary, a relational database (or maybe something like neo4j) would be the way to go.

Something like cypher could be adopted, but since it would have query parsing overhead and (more importantly) allow for the execution of inefficient queries, it would be substantially slower. I'd still be open to adding it though, because it would be "firewalled" away to a separate interface, with users still being able to use the native query language if they need full performance.

No changes to lib should be necessary, it'd be just some new endpoints exposed in bin that take in a cypher query.

**Comment by dgandhi17** [comment]
I understood that query language will be a over head if we support native query. I am ok if we can have property level comparison because for most of the app will require the native graph support to filter instead of fetch all data first and than perform on top of that. Do you think the existing vertex or edge query we can add property level queries, some what like Fluent API where parsing doesn't require. Any way most of the apps today won't want to write String queries rather they will like DSL fluent API to query. Which I think the library already provides.

Your thoughts ?

**Comment by ysimonson** [comment]
That route would compromise the idea of the native query language only exposing optimized queries. I think a separate cypher interface would be the way to go.

**Comment by ysimonson** [comment]
If you're looking for SPARQL support, I just came across this surprisingly similar project: https://github.com/oxigraph/oxigraph
