### ISSUE TITLE
Does this support flat buffers

### ISSUE THREAD

**Issue by dgandhi17** [indradb/indradb#96]
I see current implementation supports Json only,  I guess if it supports Flatbuffers it will improve overall performance

**Comment by ysimonson** [comment]
With regard to client<->server communication, these performance gains are largely actualized already via cap'n proto, which employs the same techniques as flatbuffers (and then some!) JSON is used strictly for property values, which are passed around as part of RPC requests. On this front:

1) Flatbuffers aren't possible because they assume a fixed schema ahead of time, whereas properties are schema-less. Flexbuffers would work though.
2) The small performance gain in using something other than JSON in client<->server communication is not worthwhile due to increased client complexity. Everything speaks JSON nowadays. But not everything speaks flexbuffers.

That said, it might make sense to consider using some binary equivalent to JSON for storage. Right now values are stored as raw JSON strings, when some bytes could likely be shaved by using something more efficient. Flexbuffers are an option here - [especially since serde has support for it](https://github.com/google/flatbuffers/tree/master/rust/flexbuffers). But it's likely the case that bincode would be even more efficient.

**Comment by dgandhi17** [comment]
Correct, but as the lib can be used as embedded right, was thinking to expose api's to get access through FFI from other platform, majorly from dart as Flutter is gaining cross platform support. And in case of dart it should be direct access rather than a client <-> server. Your thoughts ? I see right now there are no much lightweight graph db options for mobile or IOT platforms.

**Comment by dgandhi17** [comment]
And yes flatbuffers are being adopted by many db's as that supports ZERO copy. But schema less flatbuffers gives similar performance what JSON gives, i believe no much different.

**Comment by ysimonson** [comment]
1) Flatbuffers aren't generally use for FFI, they're used for serializing structs to be sent over the wire, i.e. client<->server communication.
2) Cap'n proto already does "zero copy".
3) If you want to use FFI, that's certainly possible thanks to rust. Though you'd have to write a bit of glue: https://doc.rust-lang.org/stable/reference/abi.html

**Comment by dgandhi17** [comment]
FFI, I mean to say a cross platform serialisation protocol will have. I saw Cap'n proto but it doesn't supported by recent new languages. And Flatbuffers supported by more languages than Cap'n proto. Any way

**Comment by ysimonson** [comment]
I don't see how switching to flatbuffers would be a net win over the current setup:

* Language support is fairly comparable to cap'n proto.
* Both employ similar techniques to maximize performance.
* Community size is fairly comparable.

If we were to reconsider the RPC layer, I think it'd be in favor of gRPC. This was experimented with in the past before settling on cap'n proto, but that was 2 years ago, and a lot has changed since then. In particular, the ecosystem around gRPC has grown quite a bit over flatbuffers and cap'n proto, and the rust tooling in particular has improved dramatically. This would come at the cost of performance and backwards compatibility though, so it hasn't been a priority.

Closing this as I don't think there's much that's actionable here, other than considering alternative storage mechanisms for properties.
